//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Технологии
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material_()
        {
            this.MaterialInProducts = new HashSet<MaterialInProduct>();
        }
    
        public int ID { get; set; }
        public string Material { get; set; }
        public Nullable<int> Material_type { get; set; }
    
        public virtual material_type_ material_type_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialInProduct> MaterialInProducts { get; set; }
    }
}
