//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Технологии
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialInProduct
    {
        public int ID { get; set; }
        public Nullable<int> id_prodiction { get; set; }
        public Nullable<int> id_material { get; set; }
    
        public virtual Material_ Material_ { get; set; }
        public virtual production_ production_ { get; set; }
    }
}
