//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Технологии
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tecnoEntities : DbContext
    {
        public tecnoEntities()
            : base("name=tecnoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Material_> Material_ { get; set; }
        public virtual DbSet<material_type_> material_type_ { get; set; }
        public virtual DbSet<MaterialInProduct> MaterialInProducts { get; set; }
        public virtual DbSet<ParthAndProd_> ParthAndProd_ { get; set; }
        public virtual DbSet<Partner_> Partner_ { get; set; }
        public virtual DbSet<Partner_type_> Partner_type_ { get; set; }
        public virtual DbSet<production_> production_ { get; set; }
        public virtual DbSet<production_type_> production_type_ { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
