//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Технологии
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partner_()
        {
            this.ParthAndProd_ = new HashSet<ParthAndProd_>();
        }
    
        public int Partner_type { get; set; }
        public string Partner_name { get; set; }
        public string Direktor { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string adress { get; set; }
        public string INN { get; set; }
        public int Rating { get; set; }
        public int ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParthAndProd_> ParthAndProd_ { get; set; }
        public virtual Partner_type_ Partner_type_ { get; set; }
    }
}
