//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Технологии
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParthAndProd_
    {
        public int ID { get; set; }
        public Nullable<int> Partner_name { get; set; }
        public Nullable<int> Production { get; set; }
        public int QuantityProd { get; set; }
    
        public virtual Partner_ Partner_ { get; set; }
        public virtual production_ production_ { get; set; }
    }
}
