//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Технологии
{
    using System;
    using System.Collections.Generic;
    
    public partial class production_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public production_()
        {
            this.MaterialInProducts = new HashSet<MaterialInProduct>();
            this.ParthAndProd_ = new HashSet<ParthAndProd_>();
        }
    
        public int Article { get; set; }
        public string Production_name { get; set; }
        public int Production_Type { get; set; }
        public double Min_price { get; set; }
        public int QuantitySklad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialInProduct> MaterialInProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParthAndProd_> ParthAndProd_ { get; set; }
        public virtual production_type_ production_type_ { get; set; }
    }
}
